[package]
name = "ceph_monitor"
version = "0.1.0"
authors = ["Chris MacNaughton <chmacnaughton@gmail.com>"]
[dependencies]
rustc-serialize = "*"
yaml-rust = "*"
time="*"
ease="*"
log = "*"
simple_logger = "*"
influent = "0.2"